pipeline {
    agent any

    stages {
        stage('Check Out Code') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/SibaniMajhi/TCS-BANK-API.git'
            }

            }
            
        stage('Run Test Cases') {
            steps {
                bat  "mvn clean test"
            }
        }
        
        stage('Publish Test Reports') {
            steps {
                junit '**/target/surefire-reports/TEST-*.xml'
            }
        }
        
        stage('Build Code') {
            steps {
                bat "mvn package -DskipTests=true"
            }
        }
        
        stage('Archieve Results') {
            steps {
                archiveArtifacts 'target/*.war'
            }
        }
    }
}


